[package]
name = "clipforge-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clipforge-core.workspace = true
clipforge-player.workspace = true
slint.workspace = true
anyhow.workspace = true
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
slint-build.workspace = true

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"
